server:
  port: 8082

  spring:
    application:
      name: API-GATEWAY

cloud:
  gateway:
    routes:


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761:/eureka